const SHORT_MOVIE_DURATION = 40;
const SHOWN_MOVIES_QUANTITY_HIGH = 12;
const SHOWN_MOVIES_QUANTITY_MID = 8;
const SHOWN_MOVIES_QUANTITY_LOW = 5;
const ADD_MOVIES_QUANTITY_HIGH = 3;
const ADD_MOVIES_QUANTITY_LOW = 2;
const DEVICE_WIDTH_HIGH = 769;
const DEVICE_WIDTH_MID = 768;
const DEVICE_WIDTH_LOW = 520;

export {
  SHORT_MOVIE_DURATION,
  SHOWN_MOVIES_QUANTITY_HIGH,
  SHOWN_MOVIES_QUANTITY_MID,
  SHOWN_MOVIES_QUANTITY_LOW,
  ADD_MOVIES_QUANTITY_HIGH,
  ADD_MOVIES_QUANTITY_LOW,
  DEVICE_WIDTH_HIGH,
  DEVICE_WIDTH_MID,
  DEVICE_WIDTH_LOW
}